stages:

  ##### DATA PREP #####

  prepare:
    cmd: python src/data.py
    params:
      - params.yaml:
        - data
        - train
    outs:
      - data/cifar10

  ##### MODEL TRAINING #####

  train_exp1:
    cmd: python src/train.py -v --experiment exp1_lenet
    deps:
      - src/train.py
      - src/data.py
      - data/cifar10
      - src/models/lenet.py
      - src/layers.py
    params:
      - params.yaml:
        - train
        - exp1_lenet
    outs:
      - models/exp1_lenet/best.pt
    metrics:
      - metrics/exp1_lenet/results.json:
          cache: false
  train_exp2:
    cmd: python src/train.py -v --experiment exp2_hybrid
    deps:
      - src/train.py
      - src/data.py
      - data/cifar10
      - src/models/hybrid.py
      - src/layers.py
    params:
      - params.yaml:
        - train
        - exp2_hybrid
    outs:
      - models/exp2_hybrid/best.pt
    metrics:
      - metrics/exp2_hybrid/results.json:
          cache: false
  train_exp3:
    cmd: python src/train.py -v --experiment exp3_alexnet
    deps:
      - src/train.py
      - src/data.py
      - data/cifar10
      - src/models/alexnet.py
      - src/layers.py
    params:
      - params.yaml:
        - train
        - exp3_alexnet
    outs:
      - models/exp3_alexnet/best.pt
    metrics:
      - metrics/exp3_alexnet/results.json:
          cache: false

  ##### MODEL EVALUATION #####

  eval_exp1:
    cmd: python src/evaluate.py -v --experiment exp1_lenet
    deps:
      - src/evaluate.py
      - src/utils.py
      - src/data.py
      - models/exp1_lenet/best.pt
    params:
      - params.yaml:
        - train
    outs:
      - metrics/exp1_lenet/confusion_matrix.pt
    metrics:
      - metrics/exp1_lenet/eval.json:
          cache: false

  eval_exp2:
    cmd: python src/evaluate.py -v --experiment exp2_hybrid
    deps:
      - src/evaluate.py
      - src/utils.py
      - src/data.py
      - models/exp2_hybrid/best.pt
    params:
      - params.yaml:
        - train
    outs:
      - metrics/exp2_hybrid/confusion_matrix.pt
    metrics:
      - metrics/exp2_hybrid/eval.json:
          cache: false

  eval_exp3:
    cmd: python src/evaluate.py -v --experiment exp3_alexnet
    deps:
      - src/evaluate.py
      - src/utils.py
      - src/data.py
      - models/exp3_alexnet/best.pt
    params:
      - params.yaml:
        - train
    outs:
      - metrics/exp3_alexnet/confusion_matrix.pt
    metrics:
      - metrics/exp3_alexnet/eval.json:
          cache: false

  ##### VISUALIZATION #####

  visualize_exp1:
    cmd: python src/visualize.py -v --experiment exp1_lenet
    deps:
      - src/visualize.py
      - src/utils.py
      - src/data.py
      - src/layers.py
      - src/models/lenet.py
      - models/exp1_lenet/best.pt
    params:
      - params.yaml:
        - train
        - visualize
    outs:
      - plots/exp1_lenet

  visualize_exp2:
    cmd: python src/visualize.py -v --experiment exp2_hybrid
    deps:
      - src/visualize.py
      - src/utils.py
      - src/data.py
      - src/layers.py
      - src/models/hybrid.py
      - models/exp2_hybrid/best.pt
    params:
      - params.yaml:
        - train
        - visualize
    outs:
      - plots/exp2_hybrid

  visualize_exp3:
    cmd: python src/visualize.py -v --experiment exp3_alexnet
    deps:
      - src/visualize.py
      - src/utils.py
      - src/data.py
      - src/layers.py
      - src/models/alexnet.py
      - models/exp3_alexnet/best.pt
    params:
      - params.yaml:
        - train
        - visualize
    outs:
      - plots/exp3_alexnet